### ISSUE TITLE
Inconsistent placeholder text colours 

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#11]
Please make Resume + DOB placeholder text the same grey as the rest 

<img width="673" alt="screen shot 2017-10-21 at 10 45 47 pm" src="https://user-images.githubusercontent.com/29152180/31858044-24404b1c-b6bc-11e7-96cf-4913b8d8051f.png">
<img width="654" alt="screen shot 2017-10-21 at 10 48 56 pm" src="https://user-images.githubusercontent.com/29152180/31858045-26451096-b6bc-11e7-8f6e-40dd4e64a7f8.png">

Thanks!

**Comment by d4l3k** [comment]
This might be a pain since the date/file selectors are provided by the browser.

**Comment by sherryyx** [comment]
@d4l3k ah ok dw about it then (y) thanks Tristan!
