### ISSUE TITLE
Add Red Academy logo

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#15]
Please add this logo to the website.

## Logo URL (Preferably SVG format)
http://redacademy.github.io/web-dev-sampler/img/red-logo.svg

## URL the Logo Should Point To
https://redacademy.com/

## Tier (Select one of Micro, Kilo, Mega, Giga)
Kilo - on same tier as Google and CA Technologies 

Thanks!

**Comment by chamkank** [comment]
Done (https://github.com/nwhacks/nwhacks2018_static/commit/15da9ea9ec0a04f353cefb26d01d6ebd08047299)
