### ISSUE TITLE
Change 'major' question to 'faculty' with dropdown

### ISSUE THREAD

**Issue by luceliu** [nwhacks/nwhacks2018_static#22]
'What faculty are you in?' instead; we don't need to know their exact majors.
Also, dropdown instead of short answer (just put the more common ones - Arts, Sauder, Science, Engineering, Forestry - and include an "Other" with a short answer, as already done in other questions)
This will make demographic stats hella easier to work with post-event.

**Comment by d4l3k** [comment]
What about for non-ubc students? Shouldn't it be a more general list than something like "Sauder"?
