### ISSUE TITLE
Increase font size of radio btn question text

### ISSUE THREAD

**Issue by luceliu** [nwhacks/nwhacks2018_static#24]
<img width="695" alt="screen shot 2017-10-30 at 9 12 17 pm" src="https://user-images.githubusercontent.com/20194766/32207133-36b67a08-bdb7-11e7-9db0-4a4b5b85e75d.png">
Would look better if it were same size as placeholder text pictured at top. thank you kindly

**Comment by chamkank** [comment]
Wait did you still want this added?

**Comment by luceliu** [comment]
yeah just wasn't sure if we needed the issue cus Sherry also put this on #dev slack

Luce
________________________________

**Comment by chamkank** [comment]
Done (https://github.com/nwhacks/nwhacks2018_static/commit/8291081ca5172132789ceb35339acb6c7fdc7eef)
