### ISSUE TITLE
Wolfram under logo

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#30]
From sponsor:  Could you add "Wolfram" under our logo? 
Thanks!

**Comment by d4l3k** [comment]
Are they the title sponsor?

**Comment by patricklinpl** [comment]
Nope, it's for wolfram language. Are we only doing that for title sponsors?

**Comment by d4l3k** [comment]
Uh, think so? Don't really know what's going on with that. Just surprised

**Comment by patricklinpl** [comment]
alright, i'll let them know it's reserved for title sponsors. Should be fine, thanks!

**Comment by chamkank** [comment]
Wait maybe they actually meant add the word "Wolfram" under their existing logo (since it's just the wolf icon right now)?
