### ISSUE TITLE
Nav bar bug 

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#31]
1) Clicking the logo in the nav bar auto-scrolls to somewhere random on the page (try clicking it it from the registration page) 

2) Navbar links don't autoscroll to quite the right location 

![nav bar](https://user-images.githubusercontent.com/29152180/32353397-a4ab126c-bffb-11e7-8ce4-f72ce0bba671.gif)

Thanks!

**Comment by yipalber** [comment]
Seems to be a problem with smoothScroll and web browser compatibility (ie. smoothScroll doesn't work in FireFox, but the links lead to the correct pages; vice versa in Chrome and Opera).

**Comment by d4l3k** [comment]
tl;dr, our smooth scroll polyfill sucks
