### ISSUE TITLE
Add 'browser not supported' page

### ISSUE THREAD

**Issue by yipalber** [nwhacks/nwhacks2018_static#33]
Instead of having a broken page (IE 11) like this:

![capture](https://user-images.githubusercontent.com/22532640/32419458-f2de2d2c-c22e-11e7-9baf-9954071716ba.JPG)

it'd nice to display a 'browser not supported' page.

**Comment by d4l3k** [comment]
Just fixed support for IE11. I only tested on Edge :/ since I figured there weren't many people using ie11. 

Turns out IE11 doesn't support `startsWith` 😢 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
