### ISSUE TITLE
static question label inconsistencies 

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#34]
Some of the questions in mentorexpo and volunteer don't have the static question label, which is also causing the text to wrap weird on mobile 
See image: 

<img width="178" alt="screen shot 2017-11-06 at 6 28 34 pm" src="https://user-images.githubusercontent.com/29152180/32469398-7e66e752-c320-11e7-89f7-9da22b9e14fa.png">

Thanks!

**Comment by d4l3k** [comment]
Yeah, I didn't have time to fix those. PRs welcome. It's pretty easy @BarCatFigaro @chamkank

**Comment by d4l3k** [comment]
@chamkank Thanks for finishing this up!
