### ISSUE TITLE
Separate Volunteer / Mentor Signup

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#5]
Could we create separate sign ups for hackers, mentors, volunteers to be displayed as buttons on the landing page?

**Comment by chamkank** [comment]
Sure, you mean for when registration opens?

**Comment by patricklinpl** [comment]
Yup

**Comment by d4l3k** [comment]
@patricklinpl 

Can you get me a list of questions you want for the volunteer/mentor sign up?

**Comment by xofeoz** [comment]
@patricklinpl do you think we should include an option to be an expo judge in the mentor application or make a separate one for that? Cause we're gonna need way more expo judges than we had last time

**Comment by patricklinpl** [comment]
@xofeoz yes good point, let's add a expo-judge option

**Comment by sherryyx** [comment]
<img width="676" alt="screen shot 2017-10-22 at 12 36 36 am" src="https://user-images.githubusercontent.com/29152180/31858253-17fb9906-b6c1-11e7-80b7-178c649434c5.png">

**Figma:**
https://www.figma.com/file/O3fGShcZs55Nbxwe65lTKrE5/nwHacks.io
