### ISSUE TITLE
.tech Domains

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#6]
Please add this logo to the website.

## Logo URL (Preferably SVG format)
<img width="842" alt="artboard 1 2x" src="https://user-images.githubusercontent.com/15319206/31696934-5ad0b938-b369-11e7-9e7e-402851a03d30.png">

[black.pdf](https://github.com/nwhacks/nwhacks2018_static/files/1393159/black.pdf)

## URL the Logo Should Point To
http://get.tech/

## Tier (Select one of Micro, Kilo, Mega, Giga)
in-kind

Thanks!

**Comment by chamkank** [comment]
Done (https://github.com/nwhacks/nwhacks2018_static/commit/723f76a14b47b71a01b2c4440c452c0a767531cb)
