### ISSUE TITLE
Page jumps when navigating with J and K

### ISSUE THREAD

**Issue by luceliu** [nwhacks/nwhacks2018_static#62]
macOS Sierra v10.12.6
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

Reproduce:
1. Click an applicant and on right side, scroll to bottom (where the bonus question and checkbox questions are) 
2. Keep hitting J until the applicant in focus is no longer visible in the left sidebar. Right side jumps to top (where name, email, etc. are)

**Comment by d4l3k** [comment]
Not sure what's causing this. There's an `if` statement to scroll the iron-list, but nothing about the right side.
