### ISSUE TITLE
Add filter/sort by submission time 

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#69]
We'll probably need to be able to see only the applicants who registered before/after first round deadline (nov 30th 11:59pm) for second round acceptances. 

Can we add a filter/sort by time option?

**Comment by d4l3k** [comment]
It's sorted by submission time already

**Comment by nick-fung** [comment]
There are still new applicants showing up though.
Anything after applicant #1824 is seems to be a second round applicant

**Comment by sherryyx** [comment]
Right, are we going to be able to sort by score and then filter out the people who applied after the deadline though? bc if I apply sort by score then some of the ppl we've started assessing for second round are mixed in

**Comment by d4l3k** [comment]
I'll add a date range filter
