### ISSUE TITLE
Daily Hive Vancouver

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#7]
Please add this logo to the website.

## Logo URL (Preferably SVG format)
[Logo Usage guidelines Sep 2017.pdf](https://github.com/nwhacks/nwhacks2018_static/files/1399599/Logo.Usage.guidelines.Sep.2017.pdf)
[DailyHive-cities2.pdf](https://github.com/nwhacks/nwhacks2018_static/files/1399600/DailyHive-cities2.pdf)

## URL the Logo Should Point To

http://dailyhive.com/vancouver

## Tier (Select one of Micro, Kilo, Mega, Giga)

Media - Sponsor

Thanks!

**Comment by chamkank** [comment]
Which existing tier do you want it in (since we don't have a media sponsor tier)? Maybe next to vidyard?
