### ISSUE TITLE
Visual indicator in left sidebar of comments on applications

### ISSUE THREAD

**Issue by luceliu** [nwhacks/nwhacks2018_static#79]
Wishlist item. Would be helpful to see an indicator (e.g. green circle with #) for applications with comments while scrolling through the left sidebar.

**EDIT**: filter to see only applications with comments + ability to archive specific comments to remove them from the filtered results

**Comment by nick-fung** [comment]
I think a filter might be easier+more useful

**Comment by luceliu** [comment]
wouldn't that be a lot like tags... tho I see ur point

**Comment by luceliu** [comment]
On second thought, the filter is a better idea. + since we have a lot of "put them on the bus" comments that are irrelevant now, the ability to "archive" those would be great

**Comment by d4l3k** [comment]
You can already use filter expressions to check for the existance of comments via `comments`.

Archiving is slightly more tricky.

**Comment by luceliu** [comment]
@d4l3k this is like an indie game with surprise features around every corner (y)
