### ISSUE TITLE
Add static labels to text fields

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#8]
Please add static labels and placeholder text to text fields. Remove the appearing floating label for consistency  with the long-answer text field (re: questions that are longer than their text fields) 

<img width="333" alt="screen shot 2017-10-21 at 10 36 03 pm" src="https://user-images.githubusercontent.com/29152180/31858056-51c64ac8-b6bc-11e7-9c3a-2de3f56672fe.png">

## Links
Questions + placeholder text
https://docs.google.com/document/d/1kuOp-Tcslw_TfsWbzCO0erRzuX0UI19Aq9s-cMtyRVQ/edit?usp=sharing 

Desired outcome: 
https://www.webcomponents.org/element/PolymerElements/paper-input/demo/demo/index.html

<img width="591" alt="screen shot 2017-10-21 at 11 54 21 pm" src="https://user-images.githubusercontent.com/29152180/31858017-38dbde0c-b6bb-11e7-9f5a-96a4838eb652.png">

Thanks!

**Comment by d4l3k** [comment]
WIP. Gonna add the placeholders tho

![2017-10-27-210159_497x386_scrot](https://user-images.githubusercontent.com/909104/32131073-19dcf772-bb5a-11e7-95df-e79bbf4726a9.png)
![2017-10-27-210137_478x335_scrot](https://user-images.githubusercontent.com/909104/32131074-19f5a588-bb5a-11e7-8260-237a1986c058.png)

**Comment by d4l3k** [comment]
/register has the placeholder text, figure it doesn't matter too much for the others right now
