### ISSUE TITLE
stdlib

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#81]
Please add this logo to the website.

## Logo URL (Preferably SVG format)
![stdlib](https://user-images.githubusercontent.com/15319206/34473688-9fad8782-ef2a-11e7-98ce-c677c8a78a3e.png)

## URL the Logo Should Point To
https://stdlib.com/

## Tier (Select one of Micro, Kilo, Mega, Giga)
Tetra

Thanks!

**Comment by chamkank** [comment]
Just to confirm, is this the title sponsor (do we want the logo next to our main nwHacks logo)?

**Comment by patricklinpl** [comment]
nope, same as Scotiabank
