### ISSUE TITLE
Add Workshop Schedule 

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#84]
Let's add the workshop schedule to the main site (under main schedule).

Please refer to [this](https://docs.google.com/spreadsheets/d/1xTwQnsVxtgJEb0RKr3-M8FBTQMb8x6EHbHhdxGQdGlk/edit#gid=0)

Info should be updated by Monday, Jan 8, 2018

Thanks!

**Comment by d4l3k** [comment]
@patricklinpl I added you to two Google calendars "nwHacks 2018" and "nwHacks 2018 - Workshops", you can add events to them in GCal and they'll automatically show up on the website
