### ISSUE TITLE
change Logistics Coordinator icon to something not money

### ISSUE THREAD

**Issue by luceliu** [nwhacks/nwhacks2018_static#88]
<img width="171" alt="screen shot 2018-03-04 at 12 44 57 pm" src="https://user-images.githubusercontent.com/20194766/36950381-f2d56eb6-1fa9-11e8-8d1f-59a35558f22f.png">

(btw where are these icons from?)
maybe a calendar or chart icon or something

**Comment by chamkank** [comment]
Good catch, that's actually supposed to be a different icon. And Sherry designed the hiring pages, you would have to ask her about the icons.
